# Site settings
title:          slamath.net
email:          mail@slamath.net
description:    ""
baseurl:        "" # the subpath of your site, e.g. /blog/
url:            "http://slamath.net" # the base hostname & protocol for your site

# Build settings
timezone:     Asia/Jakarta
future:       true
highlighter:  pygments
markdown:     kramdown
permalink:    /:categories/:title/
paginate:     10
excerpt_separator: "<!-- more -->"  # Sparator for spoiler
disqus_shortname: slamath
fb_app_id: 774529292639047

# path
path:
 css:         /asset/css/
 js:          /asset/js/
 images:      /asset/images/

# sass config
sass:
  sass_dir:   "asset/_sass"
  style:      compressed

# default front matter
defaults:
  -
    scope:
      path:   ""
      type:   "posts"
    values:
      layout: "post"
  -
    scope:
      path:   "blog"
      type:   "pages"
    values:
      layout: "category"
      is_category: 1
  -
    scope:
      path:   "blog/matematika"
      type:   "posts"
    values:
      layout: "post-math"

# Owner/author information
owner:
  name:           Slamet Aprilianto
  avatar:         avatar.jpg
  bio:            > # 
                  Just a super-noob. But let me share something i know. ;)
                  Let's talk about IT, math, japanese language, etc~
  email:          mail@slamath.net
  # Social networking accounts
  twitter:        slametapr
  facebook:       slametapr
  github:         slamath
  telegram:       slametapr
